### ISSUE TITLE
Are there plans to support Keycloak 24?

### ISSUE THREAD

**Issue by chhaysotheara** [5-stones/keycloak-email-otp#8]
Fantastic repo! 

Are there plans to support Keycloak 24?

And also, would you consider developing this into a single point of support for both SMS OTP and Email OTP, combining the strengths of two projects you mentioned in README? Many thanks!

**Comment by jspizziri** [comment]
@chhaysotheara ,

eventually. the big hold up is backwards compatibility. We need to support keycloak 22 as thats what we use. if adding support for 24 doesn't break BC with 22 then its fine.

Regarding SMS OTP. The big obstacle that I see here is that you need to work with an SMS delivery platform. AFAIK, unlike email (where there's SMTP) there's no universal SMS protocol that would allow us to build into the library the ability to support SMS with any arbitrary SMS provider. On the contrary, I think it would need to be highly opinionated and have specific integrations with specific SMS platforms. If that's true, that's not something I'm willing to take on, as it expands the surface area of this library significantly.
