### ISSUE TITLE
Email OTP for registration

### ISSUE THREAD

**Issue by nishit93-hub** [5-stones/keycloak-email-otp#9]
Hi,

Does keycloak provide a built-in Email OTP for registration? If no how can i enable it?

**Comment by jspizziri** [comment]
To the best of my knowledge, no. That's the reason we built this package.

**Comment by nishit93-hub** [comment]
Hi,

I used this authenticator, but i am getting OTP option while login not registering a new user. Attaching my custom flow.

![Screenshot from 2024-10-09 23-01-30](https://github.com/user-attachments/assets/4dd86747-ea62-4ba9-8de9-46006dfbf221)

**Comment by jspizziri** [comment]
Hello, we don't provide configuration assistance for this package. The readme contains general configuration advice. Good luck!
